# Generated by Django 3.2.8 on 2021-10-28 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
